# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde2c50ac1d7364adbce25d5de5faf131d61412a17a9811e28473d52022b23eb7af1f6ba2bff0c5f0125dc117d0cf51d2ef3f999291be5eeae97f68802eafc86

test:
  secret_key_base: 19c7d41e62aa25e275dd2daea1cf87518bc54b582001eed78be096ebbafdb30b9e9cb139928f94e1030372077ea7ded40b418bb0c7081fd6aa2b1b3e0afe7739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Rails.configuration.ENV["SECRET_KEY_BASE"] %>
